spring:
  profiles:
    active: @activatedProperties@
  application:
    name: seckilling-service
  main:
    allowBeanDefinitionOverriding: true
  jackson:
    time-zone: GMT+8
  cache:
    type: CAFFEINE
    cache-names:
    - templateImage
    caffeine:
      spec: maximumSize=500,expireAfterAccess=300s,softValues
  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB
  cloud:
    stream:
      rocketmq:
        bindings:
          seckillingOutput:
            producer:
              group: seckilling-output-group
              sync: true
          seckillingOrderInput:
            consumer:
              orderly: true
              tags: order
      bindings:
        seckillingOutput:
          destination: seckilling-topic
          content-type: application/json
        seckillingOrderInput:
          destination: seckilling-topic
          content-type: application/json
          group: seckilling-input-group-order

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml




